---

- name: 'Debian: Install APT dependencies'
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https

- name: 'Add elastic.co GPG key'
  apt_key:
    file: "/tmp/{{ elastic_gpg_file }}"
  when: elastic_repo__local_gpgkey

- name: 'Debian: Add elastic.co GPG key'
  apt_key:
    url: "{{ elastic_gpg_url }}"
  when: elastic_repo__local_gpgkey is undefined

- name: 'Debian: Add elastic.co APT repository'
  apt_repository:
    repo: "{{ elastic_apt_repo }}"
    state: present
    update_cache: yes
