---

# To be replaced by proper java role
- name: Install java
  apt:
    name: default-jre-headless
    state: latest


- name: Install Logstash
  apt:
    name: logstash
    state: "{{ logstash_package_state }}"
  notify:
    - restart logstash
