---
# tasks file for $roletemplate

- include: debian.yml
  when: ansible_os_family == 'Debian'

# Add RedHat when needed
#- include: redhat.yml
#  when: ansible_os_family == 'RedHat'

# FIXME, add configuration templating

- name: Install Logstash Plugins
  command: /usr/share/logstash/bin/logstash-plugin install --no-verify {{ item.plugin_name }}
  with_items: "{{ logstash_plugins }}"
  notify:
    - restart logstash

- name: Enable Logstash service
  service: name=logstash enabled=yes state=started
